from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
QSize, Qt)
from PySide6.QtGui import QAction, QActionGroup, QIcon
from PySide6.QtWidgets import (QMenu, QMenuBar,
QStatusBar, QToolBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(730, 500)
        MainWindow.setContextMenuPolicy(Qt.NoContextMenu)
        icon = QIcon()
        icon.addFile(u":/resources/icons/notepad.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon1 = QIcon()
        icon1.addFile(u":/resources/icons/file-new.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon2 = QIcon()
        icon2.addFile(u":/resources/icons/file-open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon3 = QIcon()
        icon3.addFile(u":/resources/icons/file-save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSaveAs = QAction(MainWindow)
        self.actionSaveAs.setObjectName(u"actionSaveAs")
        icon4 = QIcon()
        icon4.addFile(u":/resources/icons/file-save-as.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSaveAs.setIcon(icon4)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon5 = QIcon()
        icon5.addFile(u":/resources/icons/file-close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon5)
        self.actionCloseAll = QAction(MainWindow)
        self.actionCloseAll.setObjectName(u"actionCloseAll")
        icon6 = QIcon()
        icon6.addFile(u":/resources/icons/file-close-all.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCloseAll.setIcon(icon6)
        self.actionPrintPreview = QAction(MainWindow)
        self.actionPrintPreview.setObjectName(u"actionPrintPreview")
        icon7 = QIcon()
        icon7.addFile(u":/resources/icons/file-view.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrintPreview.setIcon(icon7)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon8 = QIcon()
        icon8.addFile(u":/resources/icons/file-print.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrint.setIcon(icon8)
        self.actionOptions = QAction(MainWindow)
        self.actionOptions.setObjectName(u"actionOptions")
        self.actionOptions.setEnabled(True)
        icon9 = QIcon()
        icon9.addFile(u":/resources/icons/file-options.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOptions.setIcon(icon9)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon10 = QIcon()
        icon10.addFile(u":/resources/icons/file-exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExit.setIcon(icon10)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon11 = QIcon()
        icon11.addFile(u":/resources/icons/edit-undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon11)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon12 = QIcon()
        icon12.addFile(u":/resources/icons/edit-redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon12)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon13 = QIcon()
        icon13.addFile(u":/resources/icons/edit-cut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon13)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon14 = QIcon()
        icon14.addFile(u":/resources/icons/edit-copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon14)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon15 = QIcon()
        icon15.addFile(u":/resources/icons/edit-paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon15)
        self.actionSelectAll = QAction(MainWindow)
        self.actionSelectAll.setObjectName(u"actionSelectAll")
        icon16 = QIcon()
        icon16.addFile(u":/resources/icons/edit-select-all.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSelectAll.setIcon(icon16)
        self.actionFindReplace = QAction(MainWindow)
        self.actionFindReplace.setObjectName(u"actionFindReplace")
        icon17 = QIcon()
        icon17.addFile(u":/resources/icons/edit-find-replace.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFindReplace.setIcon(icon17)
        self.actionGoto = QAction(MainWindow)
        self.actionGoto.setObjectName(u"actionGoto")
        icon18 = QIcon()
        icon18.addFile(u":/resources/icons/go-jump.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionGoto.setIcon(icon18)
        self.actionZoomRestore = QAction(MainWindow)
        self.actionZoomRestore.setObjectName(u"actionZoomRestore")
        icon19 = QIcon()
        icon19.addFile(u":/resources/icons/zoom-restore.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionZoomRestore.setIcon(icon19)
        self.actionZoomIn = QAction(MainWindow)
        self.actionZoomIn.setObjectName(u"actionZoomIn")
        icon20 = QIcon()
        icon20.addFile(u":/resources/icons/zoom-in.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionZoomIn.setIcon(icon20)
        self.actionZoomOut = QAction(MainWindow)
        self.actionZoomOut.setObjectName(u"actionZoomOut")
        icon21 = QIcon()
        icon21.addFile(u":/resources/icons/zoom-out.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionZoomOut.setIcon(icon21)
        self.actionWrapText = QAction(MainWindow)
        self.actionWrapText.setObjectName(u"actionWrapText")
        self.actionWrapText.setCheckable(True)
        self.actionWrapText.setChecked(True)
        icon22 = QIcon()
        icon22.addFile(u":/resources/icons/wrap-text.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionWrapText.setIcon(icon22)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon23 = QIcon()
        icon23.addFile(u":/resources/icons/help-about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon23)
        self.actionAlwaysTop = QAction(MainWindow)
        self.actionAlwaysTop.setObjectName(u"actionAlwaysTop")
        self.actionAlwaysTop.setCheckable(True)
        icon24 = QIcon()
        icon24.addFile(u":/resources/icons/view-dlg.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAlwaysTop.setIcon(icon24)
        self.actionShowSpaceTab = QAction(MainWindow)
        self.actionShowSpaceTab.setObjectName(u"actionShowSpaceTab")
        self.actionShowSpaceTab.setCheckable(True)
        icon25 = QIcon()
        icon25.addFile(u":/resources/icons/invisible-char.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionShowSpaceTab.setIcon(icon25)
        self.actionSummary = QAction(MainWindow)
        self.actionSummary.setObjectName(u"actionSummary")
        self.actionDateTime = QAction(MainWindow)
        self.actionDateTime.setObjectName(u"actionDateTime")
        self.actionUPPERCASE = QAction(MainWindow)
        self.actionUPPERCASE.setObjectName(u"actionUPPERCASE")
        self.actionLowercase = QAction(MainWindow)
        self.actionLowercase.setObjectName(u"actionLowercase")
        self.actionProperCase = QAction(MainWindow)
        self.actionProperCase.setObjectName(u"actionProperCase")
        self.actionRemoveEmptyLines = QAction(MainWindow)
        self.actionRemoveEmptyLines.setObjectName(u"actionRemoveEmptyLines")
        self.actionJoinLines = QAction(MainWindow)
        self.actionJoinLines.setObjectName(u"actionJoinLines")
        self.actionRemoveDuplicateLines = QAction(MainWindow)
        self.actionRemoveDuplicateLines.setObjectName(u"actionRemoveDuplicateLines")
        self.actionSortLinesAscendingOrder = QAction(MainWindow)
        self.actionSortLinesAscendingOrder.setObjectName(u"actionSortLinesAscendingOrder")
        self.actionSortLinesDescendingOrder = QAction(MainWindow)
        self.actionSortLinesDescendingOrder.setObjectName(u"actionSortLinesDescendingOrder")
        self.actionTrimTrailingSpace = QAction(MainWindow)
        self.actionTrimTrailingSpace.setObjectName(u"actionTrimTrailingSpace")
        self.actionTrimLeadingSpace = QAction(MainWindow)
        self.actionTrimLeadingSpace.setObjectName(u"actionTrimLeadingSpace")
        self.actionTabToSpace = QAction(MainWindow)
        self.actionTabToSpace.setObjectName(u"actionTabToSpace")
        self.actionRemoveSpace = QAction(MainWindow)
        self.actionRemoveSpace.setObjectName(u"actionRemoveSpace")
        self.actionWindowsCRLF = QAction(MainWindow)
        self.actionWindowsCRLF.setObjectName(u"actionWindowsCRLF")
        self.actionUnixLF = QAction(MainWindow)
        self.actionUnixLF.setObjectName(u"actionUnixLF")
        self.actionUTF8 = QAction(MainWindow)
        self.actionUTF8.setObjectName(u"actionUTF8")
        self.actionUTF8.setCheckable(True)
        self.actionUTF8.setChecked(True)
        self.actionUTF8BOM = QAction(MainWindow)
        self.actionUTF8BOM.setObjectName(u"actionUTF8BOM")
        self.actionUTF8BOM.setCheckable(True)
        self.actionUTF8BOM.setEnabled(True)
        self.actionUTF16BE = QAction(MainWindow)
        self.actionUTF16BE.setObjectName(u"actionUTF16BE")
        self.actionUTF16BE.setCheckable(True)
        self.actionUTF16BE.setEnabled(True)
        self.actionUTF16LE = QAction(MainWindow)
        self.actionUTF16LE.setObjectName(u"actionUTF16LE")
        self.actionUTF16LE.setCheckable(True)
        self.actionUTF16LE.setEnabled(True)
        self.actionWindows1251 = QAction(MainWindow)
        self.actionWindows1251.setObjectName(u"actionWindows1251")
        self.actionWindows1251.setCheckable(True)
        self.actionWindows1251.setEnabled(True)
        self.actionOEM866 = QAction(MainWindow)
        self.actionOEM866.setObjectName(u"actionOEM866")
        self.actionOEM866.setCheckable(True)

        self.actionGroupEncoding = QActionGroup(MainWindow, exclusive=True)
        utf8 = self.actionGroupEncoding.addAction(self.actionUTF8)
        utf8bom = self.actionGroupEncoding.addAction(self.actionUTF8BOM)
        utf16bebom = self.actionGroupEncoding.addAction(self.actionUTF16BE)
        utf16lebom = self.actionGroupEncoding.addAction(self.actionUTF16LE)
        windows1251 = self.actionGroupEncoding.addAction(self.actionWindows1251)
        oem866 = self.actionGroupEncoding.addAction(self.actionOEM866)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 730, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuConvertCase = QMenu(self.menuEdit)
        self.menuConvertCase.setObjectName(u"menuConvertCase")
        self.menuLineOperations = QMenu(self.menuEdit)
        self.menuLineOperations.setObjectName(u"menuLineOperations")
        self.menuBlankOperations = QMenu(self.menuEdit)
        self.menuBlankOperations.setObjectName(u"menuBlankOperations")
        self.menuEOLConversion = QMenu(self.menuEdit)
        self.menuEOLConversion.setObjectName(u"menuEOLConversion")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuZoom = QMenu(self.menuView)
        self.menuZoom.setObjectName(u"menuZoom")
        self.menuZoom.setIcon(icon19)
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuEncoding = QMenu(self.menubar)
        self.menuEncoding.setObjectName(u"menuEncoding")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarFile = QToolBar(MainWindow)
        self.toolBarFile.setObjectName(u"toolBarFile")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarFile)
        self.toolBarEdit = QToolBar(MainWindow)
        self.toolBarEdit.setObjectName(u"toolBarEdit")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarEdit)
        self.toolBarView = QToolBar(MainWindow)
        self.toolBarView.setObjectName(u"toolBarView")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarView)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEncoding.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionCloseAll)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrintPreview)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelectAll)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFindReplace)
        self.menuEdit.addAction(self.actionGoto)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDateTime)
        self.menuEdit.addAction(self.menuConvertCase.menuAction())
        self.menuEdit.addAction(self.menuBlankOperations.menuAction())
        self.menuEdit.addAction(self.menuLineOperations.menuAction())
        self.menuEdit.addAction(self.menuEOLConversion.menuAction())
        self.menuConvertCase.addAction(self.actionUPPERCASE)
        self.menuConvertCase.addAction(self.actionLowercase)
        self.menuConvertCase.addAction(self.actionProperCase)
        self.menuLineOperations.addAction(self.actionJoinLines)
        self.menuLineOperations.addAction(self.actionRemoveEmptyLines)
        self.menuLineOperations.addAction(self.actionRemoveDuplicateLines)
        self.menuLineOperations.addSeparator()
        self.menuLineOperations.addAction(self.actionSortLinesAscendingOrder)
        self.menuLineOperations.addAction(self.actionSortLinesDescendingOrder)
        self.menuBlankOperations.addAction(self.actionTrimTrailingSpace)
        self.menuBlankOperations.addAction(self.actionTrimLeadingSpace)
        self.menuBlankOperations.addAction(self.actionTabToSpace)
        self.menuBlankOperations.addAction(self.actionRemoveSpace)
        self.menuEOLConversion.addAction(self.actionWindowsCRLF)
        self.menuEOLConversion.addAction(self.actionUnixLF)
        self.menuView.addAction(self.actionAlwaysTop)
        self.menuView.addAction(self.actionShowSpaceTab)
        self.menuView.addAction(self.actionWrapText)
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menuView.addAction(self.actionSummary)
        self.menuView.addSeparator()
        self.menuZoom.addAction(self.actionZoomIn)
        self.menuZoom.addAction(self.actionZoomOut)
        self.menuZoom.addAction(self.actionZoomRestore)
        self.menuZoom.addSeparator()
        self.menuHelp.addAction(self.actionAbout)

        self.menuEncoding.addAction(utf8)
        self.menuEncoding.addAction(utf8bom)
        self.menuEncoding.addAction(utf16bebom)
        self.menuEncoding.addAction(utf16lebom)
        self.menuEncoding.addAction(windows1251)
        self.menuEncoding.addAction(oem866)

        self.toolBarFile.addAction(self.actionNew)
        self.toolBarFile.addAction(self.actionOpen)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionSave)
        self.toolBarFile.addAction(self.actionSaveAs)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionPrintPreview)
        self.toolBarFile.addAction(self.actionPrint)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionOptions)
        self.toolBarEdit.addAction(self.actionUndo)
        self.toolBarEdit.addAction(self.actionRedo)
        self.toolBarEdit.addSeparator()
        self.toolBarEdit.addAction(self.actionCut)
        self.toolBarEdit.addAction(self.actionCopy)
        self.toolBarEdit.addAction(self.actionPaste)
        self.toolBarEdit.addAction(self.actionSelectAll)
        self.toolBarEdit.addSeparator()
        self.toolBarEdit.addAction(self.actionFindReplace)
        self.toolBarEdit.addAction(self.actionGoto)
        self.toolBarEdit.addSeparator()
        self.toolBarView.addAction(self.actionAlwaysTop)
        self.toolBarView.addAction(self.actionShowSpaceTab)
        self.toolBarView.addAction(self.actionWrapText)
        self.toolBarView.addSeparator()
        self.toolBarView.addAction(self.actionZoomIn)
        self.toolBarView.addAction(self.actionZoomOut)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Notepad", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"&New", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"&Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"Save &As", None))
#if QT_CONFIG(shortcut)
        self.actionSaveAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"&Close", None))
#if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionCloseAll.setText(QCoreApplication.translate("MainWindow", u"Close &All", None))
#if QT_CONFIG(shortcut)
        self.actionCloseAll.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrintPreview.setText(QCoreApplication.translate("MainWindow", u"Print Preview", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"&Print", None))
#if QT_CONFIG(shortcut)
        self.actionPrint.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionOptions.setText(QCoreApplication.translate("MainWindow", u"Options", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"&Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"&Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"&Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionSelectAll.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
#if QT_CONFIG(shortcut)
        self.actionSelectAll.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionFindReplace.setText(QCoreApplication.translate("MainWindow", u"Find and Replace", None))
#if QT_CONFIG(shortcut)
        self.actionFindReplace.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionGoto.setText(QCoreApplication.translate("MainWindow", u"Go to", None))
#if QT_CONFIG(shortcut)
        self.actionGoto.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomRestore.setText(QCoreApplication.translate("MainWindow", u"Zoom Restore ", None))
#if QT_CONFIG(shortcut)
        self.actionZoomRestore.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+/", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomIn.setText(QCoreApplication.translate("MainWindow", u"Zoom In", None))
#if QT_CONFIG(shortcut)
        self.actionZoomIn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl++", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoomOut.setText(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
#if QT_CONFIG(shortcut)
        self.actionZoomOut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionWrapText.setText(QCoreApplication.translate("MainWindow", u"Wrap Text", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
#if QT_CONFIG(shortcut)
        self.actionAbout.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionAlwaysTop.setText(QCoreApplication.translate("MainWindow", u"Always on Top", None))
        self.actionShowSpaceTab.setText(QCoreApplication.translate("MainWindow", u"Show White Space and Tab", None))
        self.actionSummary.setText(QCoreApplication.translate("MainWindow", u"Summary", None))
        self.actionDateTime.setText(QCoreApplication.translate("MainWindow", u"Insert Date and Time", None))
#if QT_CONFIG(shortcut)
        self.actionDateTime.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionUPPERCASE.setText(QCoreApplication.translate("MainWindow", u"UPPERCASE", None))
        self.actionLowercase.setText(QCoreApplication.translate("MainWindow", u"lowercase", None))
        self.actionProperCase.setText(QCoreApplication.translate("MainWindow", u"Proper Case", None))
        self.actionRemoveEmptyLines.setText(QCoreApplication.translate("MainWindow", u"Remove Empty Lines", None))
        self.actionJoinLines.setText(QCoreApplication.translate("MainWindow", u"Join Lines", None))
        self.actionRemoveDuplicateLines.setText(QCoreApplication.translate("MainWindow", u"Remove Duplicate Lines", None))
        self.actionSortLinesAscendingOrder.setText(QCoreApplication.translate("MainWindow", u"Sort Lines Ascending Order", None))
        self.actionSortLinesDescendingOrder.setText(QCoreApplication.translate("MainWindow", u"Sort Lines Descending Order", None))
        self.actionTrimTrailingSpace.setText(QCoreApplication.translate("MainWindow", u"Trim Trailing Space", None))
        self.actionTrimLeadingSpace.setText(QCoreApplication.translate("MainWindow", u"Trim Leading Space", None))
        self.actionTabToSpace.setText(QCoreApplication.translate("MainWindow", u"Tab to Space", None))
        self.actionRemoveSpace.setText(QCoreApplication.translate("MainWindow", u"Remove Space", None))
        self.actionWindowsCRLF.setText(QCoreApplication.translate("MainWindow", u"Windows (CR LF)", None))
        self.actionUnixLF.setText(QCoreApplication.translate("MainWindow", u"Unix (LF)", None))
        self.actionUTF8.setText(QCoreApplication.translate("MainWindow", u"UTF-8", None))
        self.actionUTF8BOM.setText(QCoreApplication.translate("MainWindow", u"UTF-8 BOM", None))
        self.actionUTF16BE.setText(QCoreApplication.translate("MainWindow", u"UTF-16 BE", None))
        self.actionUTF16LE.setText(QCoreApplication.translate("MainWindow", u"UTF-16 LE", None))
        self.actionWindows1251.setText(QCoreApplication.translate("MainWindow", u"Windows 1251", None))
        self.actionOEM866.setText(QCoreApplication.translate("MainWindow", u"OEM 866", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menuConvertCase.setTitle(QCoreApplication.translate("MainWindow", u"Convert Case to", None))
        self.menuLineOperations.setTitle(QCoreApplication.translate("MainWindow", u"Line Operations", None))
        self.menuBlankOperations.setTitle(QCoreApplication.translate("MainWindow", u"Blank Operations", None))
        self.menuEOLConversion.setTitle(QCoreApplication.translate("MainWindow", u"EOL Conversion", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.menuEncoding.setTitle(QCoreApplication.translate("MainWindow", u"E&ncoding", None))
        self.toolBarFile.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.toolBarEdit.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.toolBarView.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

